name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment on every push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-22.04  # Specify a stable Ubuntu version

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (Optional if you need Node.js for build tools)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Specify the folder containing index.html
          force_orphan: true  # Creates a new commit history in gh-pages
